<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	
	<link rel="stylesheet" id="hhreplayer_css-css" href="/wp-content/plugins/hhr-plugin/assets/css/hhreplayer.css" type="text/css" media="all" />
	<script type="text/javascript" src="/wp-includes/js/jquery/jquery.js"></script>
	<script type="text/javascript" src="/wp-content/plugins/hhr-plugin/assets/js/hhreplayer.js"></script>
	<style>
		body {margin:0;padding:0;}
	</style>
</head>

<body>
	<?php require 'view.phtml'; ?>
</body>
	
</html>